# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'art.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 500)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path_btn = QtWidgets.QPushButton(self.centralwidget)
        self.path_btn.setObjectName("path_btn")
        self.horizontalLayout.addWidget(self.path_btn)
        self.path_LineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.path_LineEdit.setObjectName("path_LineEdit")
        self.horizontalLayout.addWidget(self.path_LineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.file_type_lab = QtWidgets.QLabel(self.centralwidget)
        self.file_type_lab.setObjectName("file_type_lab")
        self.horizontalLayout_2.addWidget(self.file_type_lab)
        self.V_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.V_checkBox.setObjectName("V_checkBox")
        self.horizontalLayout_2.addWidget(self.V_checkBox)
        self.VHD_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.VHD_checkBox.setObjectName("VHD_checkBox")
        self.horizontalLayout_2.addWidget(self.VHD_checkBox)
        self.C_checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.C_checkBox.setObjectName("C_checkBox")
        self.horizontalLayout_2.addWidget(self.C_checkBox)
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_2.addWidget(self.start_btn)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.file_table = QtWidgets.QTableWidget(self.centralwidget)
        self.file_table.setMinimumSize(QtCore.QSize(0, 300))
        self.file_table.setObjectName("file_table")
        self.file_table.setColumnCount(7)
        self.file_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(6, item)
        self.horizontalLayout_3.addWidget(self.file_table)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sum_lines_lab = QtWidgets.QLabel(self.centralwidget)
        self.sum_lines_lab.setObjectName("sum_lines_lab")
        self.horizontalLayout_4.addWidget(self.sum_lines_lab)
        self.sum_lines_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.sum_lines_lineEdit.setObjectName("sum_lines_lineEdit")
        self.horizontalLayout_4.addWidget(self.sum_lines_lineEdit)
        self.code_line_lab = QtWidgets.QLabel(self.centralwidget)
        self.code_line_lab.setObjectName("code_line_lab")
        self.horizontalLayout_4.addWidget(self.code_line_lab)
        self.code_lines_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.code_lines_lineEdit.setObjectName("code_lines_lineEdit")
        self.horizontalLayout_4.addWidget(self.code_lines_lineEdit)
        self.zhushi_lines_lab = QtWidgets.QLabel(self.centralwidget)
        self.zhushi_lines_lab.setObjectName("zhushi_lines_lab")
        self.horizontalLayout_4.addWidget(self.zhushi_lines_lab)
        self.zhushi_lines_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.zhushi_lines_lineEdit.setObjectName("zhushi_lines_lineEdit")
        self.horizontalLayout_4.addWidget(self.zhushi_lines_lineEdit)
        self.emp_lines_lab = QtWidgets.QLabel(self.centralwidget)
        self.emp_lines_lab.setObjectName("emp_lines_lab")
        self.horizontalLayout_4.addWidget(self.emp_lines_lab)
        self.emp_lines_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.emp_lines_lineEdit.setObjectName("emp_lines_lineEdit")
        self.horizontalLayout_4.addWidget(self.emp_lines_lineEdit)
        self.zhushilv_lab = QtWidgets.QLabel(self.centralwidget)
        self.zhushilv_lab.setObjectName("zhushilv_lab")
        self.horizontalLayout_4.addWidget(self.zhushilv_lab)
        self.zhushilv_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.zhushilv_lineEdit.setObjectName("zhushilv_lineEdit")
        self.horizontalLayout_4.addWidget(self.zhushilv_lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "注释率统计工具"))
        self.path_btn.setText(_translate("MainWindow", "选择路径"))
        self.file_type_lab.setText(_translate("MainWindow", "选择文件类型"))
        self.V_checkBox.setText(_translate("MainWindow", "Verilog"))
        self.VHD_checkBox.setText(_translate("MainWindow", "VHDL"))
        self.C_checkBox.setText(_translate("MainWindow", "C/C++"))
        self.start_btn.setText(_translate("MainWindow", "开始"))
        item = self.file_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "文件名"))
        item = self.file_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "文件路径"))
        item = self.file_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "总行数"))
        item = self.file_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "代码行数"))
        item = self.file_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "注释行数"))
        item = self.file_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "空白行数"))
        item = self.file_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "注释率"))
        self.sum_lines_lab.setText(_translate("MainWindow", "总行数"))
        self.code_line_lab.setText(_translate("MainWindow", "代码行数"))
        self.zhushi_lines_lab.setText(_translate("MainWindow", "注释行数"))
        self.emp_lines_lab.setText(_translate("MainWindow", "空白行数"))
        self.zhushilv_lab.setText(_translate("MainWindow", "注释率"))
